In [1]:
# load libraies

%run py_libraries.py

/Users/4476224/.local/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.6.0 and strictly below 2.9.0 (nightly versions are not supported).
 The versions of TensorFlow you are currently using is 2.13.0 and is not supported.
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(

WARNING:tensorflow:From /opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [2]:
# loading utility files

from utility.sv_fig import savefig
from utility.make_cm import make_confusion_matrix
from utility.get_g_result import get_gamma_results
from utility.plt_result import plot_results

In [3]:
def savefig(filename, crop = True):
    plt.savefig('{}.pdf'.format(filename))

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_row', None)

# load data
X_train = pd.read_csv('data/norm_X_train_Yes_No.csv')
X_test = pd.read_csv('data/norm_X_test_Yes_No.csv')
y_train = pd.read_csv('data/y_train_Yes_No.csv')
y_test = pd.read_csv('data/y_test_Yes_No.csv')


print(X_train.shape)

(74, 15)

In [5]:
# Print the column names as a list
print(X_train.columns.tolist())

['Age_at_Surgery', 'Race', 'Surgery', 'Smoker', 'BMI', 'NAC', 'cT', 'pT', 'cT_or_pT', 'pN', 'Bx_Histology', 'Histology', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor', 'Number_of_fragments_plated_tumor']

In [6]:
Xy_Yes_No = pd.concat([X_train, y_train], axis=1)

In [7]:
# checking number of patients not missing data

ndata_f_noMiss = Xy_Yes_No.copy()
num_complete_rows = ndata_f_noMiss.dropna().shape[0]
print(num_complete_rows)

42

In [7]:
#
col_to_scale = ['Age_at_Surgery', 'BMI', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor',]

def midas_impl(missing, col_to_scale, n_epoch):
    missing_cp = missing.copy() # make copy of missing df
    
    # scaler = MinMaxScaler().fit(missing_cp[col_to_scale]) # scale data
    scaler = StandardScaler().fit(missing_cp[col_to_scale]) # scale data
    missing_sc = scaler.transform(missing_cp[col_to_scale]) # this is an array, convert to df
    # missing_sc = missing_cp.copy()

    missing_df = pd.DataFrame({'Age_at_Surgery':missing_sc[:,0],
                               'BMI':missing_sc[:,1],
                               'Sample_weight_g_tumor':missing_sc[:,2],
                               'Tumor_digest_count_primary_tumor':missing_sc[:,3],
                               })
    
    # Extract cat columns from missing
    ext_col1 = missing_cp['Race']
    ext_col2 = missing_cp['Surgery']
    ext_col3 = missing_cp['Smoker']
    ext_col4 = missing_cp['NAC']
    ext_col5 = missing_cp['cT']
    ext_col6 = missing_cp['pT']
    ext_col7 = missing_cp['cT_or_pT']
    ext_col8 = missing_cp['pN']
    ext_col9 = missing_cp['Bx_Histology']
    ext_col10 = missing_cp['Histology']
    ext_col11 = missing_cp['Number_of_fragments_plated_tumor']
    ext_col12 = missing_cp['OverallTILGrowth']
    

    # Add the extracted cat columns to missing_df
    missing_df = pd.concat([missing_df, ext_col1.rename('Race')], axis=1)
    missing_df = pd.concat([missing_df, ext_col2.rename('Surgery')], axis=1)
    missing_df = pd.concat([missing_df, ext_col3.rename('Smoker')], axis=1)
    missing_df = pd.concat([missing_df, ext_col4.rename('NAC')], axis=1)
    missing_df = pd.concat([missing_df, ext_col5.rename('cT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col6.rename('pT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col7.rename('cT_or_pT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col8.rename('pN')], axis=1)
    missing_df = pd.concat([missing_df, ext_col9.rename('Bx_Histology')], axis=1)
    missing_df = pd.concat([missing_df, ext_col10.rename('Histology')], axis=1)
    missing_df = pd.concat([missing_df, ext_col11.rename('Number_of_fragments_plated_tumor')], axis=1)
    missing_df = pd.concat([missing_df, ext_col12.rename('OverallTILGrowth')], axis=1)
    

    missing_df.to_csv('missing_train.csv')
    data_0 = pd.read_csv('missing_train.csv')
    data_0.columns.str.strip()

    categorical = ['Race','Surgery','Smoker','NAC','cT','pT','cT_or_pT','pN','Bx_Histology','Histology','Number_of_fragments_plated_tumor','OverallTILGrowth']
    
    data_cat, cat_cols_list = md.cat_conv(data_0[categorical])

    data_0.drop(categorical, axis = 1, inplace = True)
    constructor_list = [data_0]
    constructor_list.append(data_cat)
    data_in = pd.concat(constructor_list, axis=1)

    na_loc = data_in.isnull()
    data_in[na_loc] = np.nan

    # imputer = md.Midas(layer_structure = [128,128], vae_layer = True, seed = 89, input_drop = 0.75, learn_rate = 0.0001)
    imputer = md.Midas(layer_structure = [128,128], vae_layer = False, seed = 42, input_drop = 0.75, learn_rate = 0.001)
    imputer.build_model(data_in, softmax_columns = cat_cols_list)
    imputer.train_model(training_epochs = n_epoch)

    # do not update M
    imputations = imputer.generate_samples(m=20).output_list

    flat_cats = [cat for variable in cat_cols_list for cat in variable]
    for i in range(len(imputations)):
        tmp_cat = [imputations[i][x].idxmax(axis=1) for x in cat_cols_list]
        cat_df = pd.DataFrame({categorical[i]:tmp_cat[i] for i in range(len(categorical))})
        imputations[i] = pd.concat([imputations[i], cat_df], axis = 1).drop(flat_cats, axis = 1)
        
    # Implementing an efficient way to replace 'Column_name_Num' with Num in every data_item whose column is 'Column_name'    
    # Loop through all imputations
    for i in range(len(imputations)):
        df = imputations[i]
        
        # Process each column independently
        for col in df.columns:
            
            # Only operate on string/object columns
            if df[col].dtype == 'object':
                # Pattern: match "ColumnName_Number"
                pattern = rf'^{re.escape(col)}_(.+)$'
                # pattern = rf'^{re.escape(col)}_(\d+)$'
                
                df[col] = df[col].str.replace(
                    pattern,
                    r'\1',
                    regex=True
                )
                
        # Optional: convert to numeric if desired
        df = df.apply(pd.to_numeric, errors='ignore')
        imputations[i] = df

    # de-bugging code
    # save one of the imputation files

    # rescale imputations
    imputations[0][col_to_scale] = scaler.inverse_transform(imputations[0][col_to_scale])
    imputations[1][col_to_scale] = scaler.inverse_transform(imputations[1][col_to_scale])
    imputations[2][col_to_scale] = scaler.inverse_transform(imputations[2][col_to_scale])
    imputations[3][col_to_scale] = scaler.inverse_transform(imputations[3][col_to_scale])
    imputations[4][col_to_scale] = scaler.inverse_transform(imputations[4][col_to_scale])
    imputations[5][col_to_scale] = scaler.inverse_transform(imputations[5][col_to_scale])
    imputations[6][col_to_scale] = scaler.inverse_transform(imputations[6][col_to_scale])
    imputations[7][col_to_scale] = scaler.inverse_transform(imputations[7][col_to_scale])
    imputations[8][col_to_scale] = scaler.inverse_transform(imputations[8][col_to_scale])
    imputations[9][col_to_scale] = scaler.inverse_transform(imputations[9][col_to_scale])
    imputations[10][col_to_scale] = scaler.inverse_transform(imputations[10][col_to_scale])
    imputations[11][col_to_scale] = scaler.inverse_transform(imputations[11][col_to_scale])
    imputations[12][col_to_scale] = scaler.inverse_transform(imputations[12][col_to_scale])
    imputations[13][col_to_scale] = scaler.inverse_transform(imputations[13][col_to_scale])
    imputations[14][col_to_scale] = scaler.inverse_transform(imputations[14][col_to_scale])
    imputations[15][col_to_scale] = scaler.inverse_transform(imputations[15][col_to_scale])
    imputations[16][col_to_scale] = scaler.inverse_transform(imputations[16][col_to_scale])
    imputations[17][col_to_scale] = scaler.inverse_transform(imputations[17][col_to_scale])
    imputations[18][col_to_scale] = scaler.inverse_transform(imputations[18][col_to_scale])
    imputations[19][col_to_scale] = scaler.inverse_transform(imputations[19][col_to_scale])

    n=0
    for i in imputations:
        file_out_csv = "midas_train/midas_train_" + str(n) + ".csv"
        i.to_csv(file_out_csv, index=False)
        n += 1

    df0 = pd.read_csv('midas_train/midas_train_0.csv'); df0 = df0.iloc[:,1:]
    df1 = pd.read_csv('midas_train/midas_train_1.csv'); df1 = df1.iloc[:,1:]
    df2 = pd.read_csv('midas_train/midas_train_2.csv'); df2 = df2.iloc[:,1:]
    df3 = pd.read_csv('midas_train/midas_train_3.csv'); df3 = df3.iloc[:,1:]
    df4 = pd.read_csv('midas_train/midas_train_4.csv'); df4 = df4.iloc[:,1:]
    df5 = pd.read_csv('midas_train/midas_train_5.csv'); df5 = df5.iloc[:,1:]
    df6 = pd.read_csv('midas_train/midas_train_6.csv'); df6 = df6.iloc[:,1:]
    df7 = pd.read_csv('midas_train/midas_train_7.csv'); df7 = df7.iloc[:,1:]
    df8 = pd.read_csv('midas_train/midas_train_8.csv'); df8 = df8.iloc[:,1:]
    df9 = pd.read_csv('midas_train/midas_train_9.csv'); df9 = df9.iloc[:,1:]
    df10 = pd.read_csv('midas_train/midas_train_10.csv'); df10 = df10.iloc[:,1:]
    df11 = pd.read_csv('midas_train/midas_train_11.csv'); df11 = df11.iloc[:,1:]
    df12 = pd.read_csv('midas_train/midas_train_12.csv'); df12 = df12.iloc[:,1:]
    df13 = pd.read_csv('midas_train/midas_train_13.csv'); df13 = df13.iloc[:,1:]
    df14 = pd.read_csv('midas_train/midas_train_14.csv'); df14 = df14.iloc[:,1:]
    df15 = pd.read_csv('midas_train/midas_train_15.csv'); df15 = df15.iloc[:,1:]
    df16 = pd.read_csv('midas_train/midas_train_16.csv'); df16 = df16.iloc[:,1:]
    df17 = pd.read_csv('midas_train/midas_train_17.csv'); df17 = df17.iloc[:,1:]
    df18 = pd.read_csv('midas_train/midas_train_18.csv'); df18 = df18.iloc[:,1:]
    df19 = pd.read_csv('midas_train/midas_train_19.csv'); df19 = df19.iloc[:,1:]

    # Initialize the output dataframe with the same dimensions
    output_df = pd.DataFrame(index=df0.index, columns=df0.columns)

    # Process continuous columns
    for col in df1.columns[:4]:
        output_df[col] = (abs(df0[col]) + abs(df1[col]) + abs(df2[col]) + abs(df3[col]) + abs(df4[col]) + 
                          abs(df5[col]) + abs(df6[col]) + abs(df7[col]) + abs(df8[col]) + abs(df9[col]) + 
                         abs(df10[col]) + abs(df11[col]) + abs(df12[col]) + abs(df13[col]) + abs(df14[col]) + 
                          abs(df15[col]) + abs(df16[col]) + abs(df17[col]) + abs(df18[col]) + abs(df19[col])) / 20

    # Process categorical columns
    for col in df1.columns[4:]:
        output_df[col] = pd.concat([df0[col],df1[col],df2[col],df3[col],df4[col],df5[col],df6[col],df7[col],df8[col],df9[col],
                                   df10[col],df11[col],df12[col],df13[col],df14[col],df15[col],df16[col],df17[col],df18[col],df19[col]], axis=1).median(axis=1)
        

    # Write the output dataframe to a CSV file
    output_df.to_csv('output_train.csv', index=False)

    # re-order cols in output_df
    output_df_re = output_df[['Age_at_Surgery', 'Race', 'Surgery', 'Smoker', 'BMI', 'NAC', 'cT', 'pT', 'cT_or_pT', 'pN', 
                              'Bx_Histology', 'Histology', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor', 
                              'Number_of_fragments_plated_tumor','OverallTILGrowth']].copy()

    return output_df_re

In [8]:
# calculate proportion of missingness in ndata_noR

# total num of NaN in the ndata_noR
total_nan_count = X_train.isna().sum().sum()

# total num of cells in ndata_noR
total_cells = X_train.size

# proportion of NaN
NaN_proportion = total_nan_count / total_cells

print('NaN_proportions:',NaN_proportion)

NaN_proportions: 0.047747747747747746

In [9]:
# 4.05% missingness

Xy_Yes_No_md = midas_impl(Xy_Yes_No, col_to_scale, 200)

Size index: [5, 3, 2, 4, 2, 7, 10, 12, 5, 9, 11, 14, 2]

Computation graph constructed

Metal device set to: Apple M1 Pro
Model initialised

Epoch: 0 , loss: 67.66642189025879
Epoch: 1 , loss: 59.41488742828369
Epoch: 2 , loss: 59.09819030761719
Epoch: 3 , loss: 51.62409973144531
Epoch: 4 , loss: 51.36961650848389
Epoch: 5 , loss: 47.4639835357666
Epoch: 6 , loss: 51.12513828277588
Epoch: 7 , loss: 48.95879364013672
Epoch: 8 , loss: 48.2608118057251
Epoch: 9 , loss: 44.72664260864258
Epoch: 10 , loss: 46.1571626663208
Epoch: 11 , loss: 42.634315490722656
Epoch: 12 , loss: 41.700480461120605
Epoch: 13 , loss: 40.28152084350586
Epoch: 14 , loss: 41.20472431182861
Epoch: 15 , loss: 44.391783714294434
Epoch: 16 , loss: 42.36011791229248
Epoch: 17 , loss: 43.47174835205078
Epoch: 18 , loss: 44.14745044708252
Epoch: 19 , loss: 42.0169095993042
Epoch: 20 , loss: 43.53757286071777
Epoch: 21 , loss: 43.125990867614746
Epoch: 22 , loss: 41.96644973754883
Epoch: 23 , loss: 40.13304615020752
Epoch: 24 , loss: 38.70580863952637
Epoch: 25 , loss: 37.75294780731201
Epoch: 26 , loss: 54.90584945678711
Epoch: 27 , loss: 41.97405529022217
Epoch: 28 , loss: 36.76167297363281
Epoch: 29 , loss: 40.1870698928833
Epoch: 30 , loss: 40.03451633453369
Epoch: 31 , loss: 38.565531730651855
Epoch: 32 , loss: 39.872610092163086
Epoch: 33 , loss: 37.913612365722656
Epoch: 34 , loss: 38.907320976257324
Epoch: 35 , loss: 40.88425922393799
Epoch: 36 , loss: 37.848942279815674
Epoch: 37 , loss: 39.14143085479736
Epoch: 38 , loss: 35.787006855010986
Epoch: 39 , loss: 38.722217082977295
Epoch: 40 , loss: 37.88200569152832
Epoch: 41 , loss: 37.09496784210205
Epoch: 42 , loss: 37.53320026397705
Epoch: 43 , loss: 37.50247764587402
Epoch: 44 , loss: 36.26101303100586
Epoch: 45 , loss: 36.94416904449463
Epoch: 46 , loss: 38.28973388671875
Epoch: 47 , loss: 38.813398361206055
Epoch: 48 , loss: 38.03727722167969
Epoch: 49 , loss: 35.570268630981445
Epoch: 50 , loss: 34.50783634185791
Epoch: 51 , loss: 37.45757293701172
Epoch: 52 , loss: 38.944366455078125
Epoch: 53 , loss: 36.25309371948242
Epoch: 54 , loss: 36.60134315490723
Epoch: 55 , loss: 35.0064811706543
Epoch: 56 , loss: 36.25336933135986
Epoch: 57 , loss: 39.49134063720703
Epoch: 58 , loss: 34.77917957305908
Epoch: 59 , loss: 39.93294429779053
Epoch: 60 , loss: 36.62966442108154
Epoch: 61 , loss: 40.60372447967529
Epoch: 62 , loss: 37.43979835510254
Epoch: 63 , loss: 36.69228553771973
Epoch: 64 , loss: 34.56260013580322
Epoch: 65 , loss: 35.44381046295166
Epoch: 66 , loss: 49.202012062072754
Epoch: 67 , loss: 45.6949987411499
Epoch: 68 , loss: 36.191189765930176
Epoch: 69 , loss: 35.480711936950684
Epoch: 70 , loss: 34.2737979888916
Epoch: 71 , loss: 35.631489753723145
Epoch: 72 , loss: 39.14853763580322
Epoch: 73 , loss: 35.68698787689209
Epoch: 74 , loss: 34.8827018737793
Epoch: 75 , loss: 36.3253116607666
Epoch: 76 , loss: 37.354658126831055
Epoch: 77 , loss: 39.41457462310791
Epoch: 78 , loss: 35.47678565979004
Epoch: 79 , loss: 36.69787120819092
Epoch: 80 , loss: 35.63948917388916
Epoch: 81 , loss: 34.132044315338135
Epoch: 82 , loss: 34.71395969390869
Epoch: 83 , loss: 39.53197383880615
Epoch: 84 , loss: 34.51539754867554
Epoch: 85 , loss: 35.23525333404541
Epoch: 86 , loss: 35.97727108001709
Epoch: 87 , loss: 32.17862892150879
Epoch: 88 , loss: 34.02587699890137
Epoch: 89 , loss: 41.43966293334961
Epoch: 90 , loss: 36.60278272628784
Epoch: 91 , loss: 38.918246269226074
Epoch: 92 , loss: 32.533984661102295
Epoch: 93 , loss: 34.719069480895996
Epoch: 94 , loss: 35.40927505493164
Epoch: 95 , loss: 35.25096416473389
Epoch: 96 , loss: 32.75663423538208
Epoch: 97 , loss: 36.57932424545288
Epoch: 98 , loss: 33.79349946975708
Epoch: 99 , loss: 32.69767904281616
Epoch: 100 , loss: 31.16942834854126
Epoch: 101 , loss: 38.017208099365234
Epoch: 102 , loss: 37.357216358184814
Epoch: 103 , loss: 36.44554042816162
Epoch: 104 , loss: 35.460936546325684
Epoch: 105 , loss: 35.59921455383301
Epoch: 106 , loss: 35.172484397888184
Epoch: 107 , loss: 36.147499084472656
Epoch: 108 , loss: 34.43195343017578
Epoch: 109 , loss: 33.43891906738281
Epoch: 110 , loss: 34.28133773803711
Epoch: 111 , loss: 37.040555000305176
Epoch: 112 , loss: 36.744741916656494
Epoch: 113 , loss: 34.414406299591064
Epoch: 114 , loss: 34.97537899017334
Epoch: 115 , loss: 33.13493728637695
Epoch: 116 , loss: 36.14418029785156
Epoch: 117 , loss: 35.77218198776245
Epoch: 118 , loss: 34.97786521911621
Epoch: 119 , loss: 32.60439872741699
Epoch: 120 , loss: 36.273791790008545
Epoch: 121 , loss: 35.37312841415405
Epoch: 122 , loss: 31.669612407684326
Epoch: 123 , loss: 34.76016283035278
Epoch: 124 , loss: 35.59241580963135
Epoch: 125 , loss: 35.25294589996338
Epoch: 126 , loss: 37.8330602645874
Epoch: 127 , loss: 36.56094932556152
Epoch: 128 , loss: 35.955078125
Epoch: 129 , loss: 32.444453716278076
Epoch: 130 , loss: 33.28297281265259
Epoch: 131 , loss: 40.01438045501709
Epoch: 132 , loss: 37.08305644989014
Epoch: 133 , loss: 31.133310794830322
Epoch: 134 , loss: 39.11099815368652
Epoch: 135 , loss: 38.809743881225586
Epoch: 136 , loss: 31.47417449951172
Epoch: 137 , loss: 33.51653289794922
Epoch: 138 , loss: 34.018221855163574
Epoch: 139 , loss: 35.89484214782715
Epoch: 140 , loss: 31.498404502868652
Epoch: 141 , loss: 38.37925577163696
Epoch: 142 , loss: 35.303054332733154
Epoch: 143 , loss: 36.17971897125244
Epoch: 144 , loss: 31.07338047027588
Epoch: 145 , loss: 33.59507656097412
Epoch: 146 , loss: 31.885587215423584
Epoch: 147 , loss: 35.17116594314575
Epoch: 148 , loss: 33.85323905944824
Epoch: 149 , loss: 32.90941047668457
Epoch: 150 , loss: 30.749573707580566
Epoch: 151 , loss: 31.5435733795166
Epoch: 152 , loss: 33.64100503921509
Epoch: 153 , loss: 30.463214874267578
Epoch: 154 , loss: 38.40500259399414
Epoch: 155 , loss: 35.136770248413086
Epoch: 156 , loss: 32.78288555145264
Epoch: 157 , loss: 34.32027530670166
Epoch: 158 , loss: 33.329328536987305
Epoch: 159 , loss: 35.36597156524658
Epoch: 160 , loss: 33.53076648712158
Epoch: 161 , loss: 32.3230562210083
Epoch: 162 , loss: 32.7709846496582
Epoch: 163 , loss: 36.31157207489014
Epoch: 164 , loss: 35.09200572967529
Epoch: 165 , loss: 39.85061502456665
Epoch: 166 , loss: 31.712050914764404
Epoch: 167 , loss: 30.893954277038574
Epoch: 168 , loss: 31.23651885986328
Epoch: 169 , loss: 31.047165870666504
Epoch: 170 , loss: 32.607540130615234
Epoch: 171 , loss: 34.554935455322266
Epoch: 172 , loss: 33.884419441223145
Epoch: 173 , loss: 33.355756759643555
Epoch: 174 , loss: 35.23392963409424
Epoch: 175 , loss: 34.4287805557251
Epoch: 176 , loss: 34.163405418395996
Epoch: 177 , loss: 33.08787441253662
Epoch: 178 , loss: 33.41443109512329
Epoch: 179 , loss: 32.29511070251465
Epoch: 180 , loss: 32.08381986618042
Epoch: 181 , loss: 33.79120397567749
Epoch: 182 , loss: 31.462668418884277
Epoch: 183 , loss: 34.27519607543945
Epoch: 184 , loss: 32.55630350112915
Epoch: 185 , loss: 32.8813591003418
Epoch: 186 , loss: 33.86191987991333
Epoch: 187 , loss: 32.64974498748779
Epoch: 188 , loss: 34.170594215393066
Epoch: 189 , loss: 31.39335536956787
Epoch: 190 , loss: 36.24796533584595
Epoch: 191 , loss: 33.91044473648071
Epoch: 192 , loss: 35.1204891204834
Epoch: 193 , loss: 33.30313158035278
Epoch: 194 , loss: 34.06014394760132
Epoch: 195 , loss: 30.19381332397461
Epoch: 196 , loss: 31.458199501037598
Epoch: 197 , loss: 30.014121532440186
Epoch: 198 , loss: 29.811459064483643
Epoch: 199 , loss: 31.53251886367798
Training complete. Saving file...

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Model saved in file: tmp/MIDAS
INFO:tensorflow:Restoring parameters from tmp/MIDAS
Model restored.

In [10]:
Xy_Yes_No_md

,Age_at_Surgery,Race,Surgery,Smoker,BMI,NAC,cT,pT,cT_or_pT,pN,Bx_Histology,Histology,Sample_weight_g_tumor,Tumor_digest_count_primary_tumor,Number_of_fragments_plated_tumor,OverallTILGrowth
0,77.0,1.0,1.0,0.0,23.170000,1.0,4.0,9.0,9.0,0.0,1.0,1.0,0.840,3020000.0,6.0,1.0
1,81.0,1.0,2.0,1.0,28.580000,0.0,1.0,1.0,1.0,1.0,1.0,11.0,0.180,1420000.0,9.0,0.0
2,84.0,1.0,1.0,0.0,28.110000,0.0,4.0,9.0,9.0,4.0,4.0,6.0,0.070,350000.0,12.0,1.0
3,70.0,1.0,1.0,0.0,28.100000,0.0,4.0,8.0,8.0,0.0,1.0,4.0,3.570,55000000.0,24.0,1.0
4,45.0,1.0,2.0,0.0,22.110000,0.0,2.0,3.0,2.0,4.0,1.0,1.0,1.310,7160000.0,18.0,0.0
5,58.0,5.0,1.0,1.0,25.960000,1.0,4.0,11.0,4.0,1.0,6.0,6.0,0.600,2500000.0,12.0,0.0
6,78.0,1.0,1.0,0.0,26.500000,1.0,4.0,11.0,11.0,0.0,1.0,1.0,0.710,2200000.0,16.0,1.0
7,73.0,1.0,1.0,1.0,33.950000,0.0,4.0,5.0,4.0,1.0,1.0,1.0,0.000,2000000.0,10.0,0.0
8,69.0,1.0,1.0,1.0,34.210000,0.0,4.0,3.0,4.0,0.0,1.0,1.0,1.300,2800000.0,6.0,1.0
9,73.0,1.0,1.0,1.0,26.610000,1.0,10.0,11.0,10.0,0.0,4.0,1.0,3.030,26000000.0,24.0,1.0
10,65.0,1.0,1.0,1.0,36.800000,1.0,4.0,8.0,8.0,0.0,1.0,4.0,1.640,90000000.0,24.0,1.0
11,64.0,1.0,1.0,2.0,20.360000,0.0,7.0,11.0,7.0,3.0,1.0,1.0,1.380,4250000.0,24.0,1.0
12,68.0,1.0,1.0,1.0,21.050000,1.0,4.0,6.0,4.0,0.0,1.0,1.0,1.660,60000000.0,24.0,0.0
13,51.0,1.0,1.0,2.0,32.090000,1.0,7.0,6.0,7.0,0.0,4.0,4.0,0.810,1190000.0,9.0,1.0
14,73.0,1.0,1.0,3.0,22.970000,1.0,4.0,9.0,9.0,0.0,1.0,1.0,0.610,1650000.0,24.0,1.0
15,76.0,1.0,1.0,1.0,30.520000,0.0,7.0,6.0,7.0,0.0,5.0,1.0,0.000,3000000.0,24.0,0.0
16,65.0,1.0,2.0,3.0,52.020000,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.230,0.0,4.0,1.0
17,75.0,1.0,1.0,0.0,28.350000,1.0,7.0,8.0,8.0,0.0,1.0,1.0,0.000,1000000.0,12.0,1.0
18,59.0,1.0,2.0,1.0,25.060000,0.0,7.0,6.0,7.0,0.0,1.0,1.0,5.210,23200000.0,6.0,1.0
19,47.0,2.0,1.0,3.0,22.530000,1.0,10.0,9.0,9.0,1.0,1.0,1.0,0.000,0.0,24.0,0.0
20,79.0,1.0,2.0,1.0,23.760000,0.0,3.0,1.0,3.0,1.0,1.0,1.0,0.290,8400000.0,8.0,0.0
21,76.0,1.0,1.0,3.0,26.570000,0.0,6.0,8.0,8.0,2.0,11.0,7.0,0.490,1120000.0,18.0,1.0
22,73.0,1.0,2.0,0.0,34.688695,0.0,1.0,3.0,1.0,0.0,1.0,1.0,0.000,0.0,3.0,0.0
23,45.0,1.0,2.0,1.0,52.120000,0.0,1.0,11.0,1.0,0.0,1.0,1.0,0.070,0.0,2.0,0.0
24,76.0,1.0,1.0,1.0,24.410000,0.0,4.0,6.0,4.0,0.0,1.0,1.0,0.540,2500000.0,24.0,1.0
25,61.0,1.0,2.0,0.0,27.450000,0.0,4.0,9.0,4.0,0.0,1.0,1.0,0.000,0.0,0.0,0.0
26,60.0,1.0,1.0,1.0,26.370000,1.0,10.0,9.0,10.0,0.0,4.0,4.0,1.120,1400000.0,24.0,1.0
27,50.0,1.0,1.0,2.0,28.950000,1.0,7.0,9.0,9.0,0.0,4.0,7.0,0.200,200000.0,6.0,1.0
28,61.0,1.0,2.0,1.0,30.210000,0.0,2.0,8.0,2.0,0.0,1.0,1.0,0.340,150000.0,6.0,1.0
29,60.0,1.0,1.0,2.0,24.100000,0.0,3.0,9.0,3.0,1.0,1.0,4.0,0.000,3500000.0,24.0,1.0
30,54.0,1.0,2.0,3.0,33.580000,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.548,0.0,12.0,1.0
31,77.0,1.0,1.0,1.0,43.910000,0.0,1.0,11.0,11.0,0.0,1.0,1.0,0.000,0.0,0.0,0.0
32,75.0,1.0,1.0,1.0,27.990000,1.0,4.0,9.0,4.0,3.0,1.0,1.0,0.000,1560000.0,24.0,1.0
33,52.0,2.0,1.0,2.0,20.840000,1.0,10.0,11.0,11.0,0.0,1.0,12.0,5.060,33600000.0,24.0,1.0
34,68.0,1.0,1.0,0.0,21.320000,1.0,7.0,11.0,7.0,0.0,1.0,2.0,0.340,465000.0,6.0,1.0
35,72.0,1.0,2.0,1.0,32.730000,0.0,3.0,5.0,5.0,0.0,1.0,1.0,1.000,1000000.0,6.0,0.0
36,69.0,1.0,2.0,2.0,24.130000,0.0,3.0,9.0,3.0,0.0,1.0,1.0,0.000,0.0,0.0,1.0
37,28.0,1.0,1.0,0.0,17.780000,1.0,10.0,11.0,11.0,2.0,2.0,2.0,0.400,1300000.0,12.0,1.0
38,64.0,1.0,1.0,2.0,21.051999,1.0,4.0,11.0,11.0,0.0,1.0,10.0,0.830,2400000.0,8.0,0.0
39,75.0,1.0,2.0,0.0,28.500000,0.0,3.0,3.0,3.0,0.0,1.0,1.0,0.340,3000000.0,6.0,1.0
40,57.0,1.0,1.0,1.0,33.760000,0.0,4.0,9.0,4.0,3.0,10.0,10.0,0.460,5000000.0,12.0,1.0
41,64.0,1.0,1.0,1.0,28.960000,1.0,4.0,9.0,9.0,0.0,2.0,4.0,10.950,95700000.0,24.0,0.0
42,60.0,1.0,2.0,1.0,4.890000,0.0,3.0,6.0,3.0,0.0,1.0,1.0,0.000,0.0,0.0,0.0
43,69.0,1.0,1.0,1.0,33.270000,1.0,4.0,0.0,4.0,0.0,8.0,1.0,0.610,570000.0,24.0,1.0
44,74.0,1.0,1.0,1.0,43.100000,0.0,10.0,1.0,1.0,0.0,1.0,1.0,1.010,27600000.0,24.0,1.0
45,71.0,1.0,2.0,2.0,39.770000,0.0,1.0,3.0,1.0,1.0,1.0,1.0,0.562,0.0,12.0,1.0
46,64.0,1.0,1.0,2.0,38.370000,1.0,4.0,6.0,6.0,0.0,1.0,1.0,0.190,84000.0,18.0,0.0
47,84.0,1.0,1.0,1.0,24.380000,0.0,4.0,12.0,12.0,1.0,1.0,4.0,4.110,15100000.0,32.0,1.0
48,70.0,1.0,1.0,1.0,36.620000,1.0,4.0,6.0,6.0,0.0,6.0,4.0,2.790,100000000.0,24.0,1.0
49,63.0,1.0,1.0,0.0,34.730000,1.0,4.0,0.0,4.0,0.0,1.0,0.0,1.340,1000000.0,10.0,0.0
50,87.0,1.0,2.0,2.0,22.750000,0.0,3.0,1.0,3.0,0.0,1.0,1.0,0.460,5000000.0,6.0,0.0
51,63.0,1.0,1.0,1.0,22.690000,1.0,7.0,1.0,7.0,0.0,1.0,1.0,0.000,40200000.0,12.0,1.0
52,79.0,1.0,2.0,1.0,27.730000,0.0,4.0,9.0,4.0,0.0,1.0,1.0,2.270,9900000.0,8.0,1.0
53,63.0,1.0,1.0,1.0,29.940000,1.0,4.0,9.0,9.0,0.0,1.0,7.0,0.130,1200000.0,12.0,1.0
54,77.0,1.0,2.0,1.0,25.560000,0.0,1.0,9.0,1.0,0.0,1.0,1.0,0.000,0.0,0.0,0.0
55,57.0,1.0,1.0,1.0,31.860000,0.0,1.0,1.0,1.0,0.0,1.0,1.0,2.400,255000000.0,24.0,1.0
56,90.0,1.0,1.0,3.0,25.820000,1.0,3.0,9.0,9.0,4.0,1.0,1.0,0.930,2500000.0,12.0,0.0
57,71.0,1.0,1.0,1.0,20.190000,1.0,4.0,8.0,4.0,3.0,1.0,1.0,0.000,210000.0,12.0,0.0
58,76.0,1.0,1.0,3.0,31.860000,0.0,3.0,9.0,9.0,0.0,5.0,1.0,0.540,7400000.0,18.0,1.0
59,36.0,1.0,1.0,1.0,45.590000,0.0,3.0,3.0,3.0,0.0,1.0,1.0,0.970,14000000.0,24.0,1.0
60,60.0,1.0,2.0,2.0,30.770000,1.0,4.0,5.0,4.0,0.0,1.0,13.0,0.000,1500000.0,24.0,1.0
61,76.0,1.0,2.0,3.0,32.200000,0.0,3.0,4.0,4.0,0.0,1.0,1.0,0.560,14500000.0,4.0,1.0
62,71.0,1.0,1.0,0.0,40.640000,1.0,7.0,5.0,5.0,0.0,1.0,1.0,0.000,0.0,0.0,0.0
63,69.0,1.0,2.0,0.0,25.990000,0.0,3.0,1.0,3.0,0.0,1.0,1.0,0.000,2000000.0,6.0,1.0
64,81.0,1.0,2.0,1.0,28.740000,0.0,1.0,9.0,1.0,0.0,1.0,1.0,0.000,0.0,1.0,0.0
65,67.0,1.0,1.0,1.0,36.760000,1.0,4.0,6.0,6.0,2.0,1.0,5.0,0.870,200000.0,24.0,1.0
66,79.0,1.0,1.0,1.0,39.580000,0.0,7.0,11.0,11.0,0.0,9.0,10.0,2.340,1750000.0,24.0,1.0
67,79.0,1.0,1.0,1.0,21.890000,0.0,7.0,9.0,9.0,0.0,1.0,6.0,1.480,11500000.0,24.0,1.0
68,88.0,1.0,1.0,1.0,35.336983,1.0,10.0,9.0,10.0,0.0,1.0,1.0,0.480,8900000.0,24.0,0.0
69,62.0,1.0,1.0,1.0,24.910000,1.0,4.0,11.0,4.0,1.0,1.0,10.0,0.180,1170000.0,6.0,0.0
70,76.0,1.0,1.0,0.0,33.360000,0.0,4.0,6.0,6.0,0.0,4.0,1.0,0.570,31000000.0,24.0,1.0
71,55.0,1.0,1.0,1.0,26.600000,1.0,4.0,9.0,9.0,2.0,4.0,1.0,0.490,31500000.0,12.0,1.0
72,77.0,1.0,2.0,1.0,26.170000,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.670,64000.0,24.0,0.0
73,91.0,1.0,1.0,0.0,19.220000,0.0,4.0,5.0,4.0,3.0,1.0,1.0,0.710,1300000.0,12.0,1.0

In [11]:
# save to csv file

# 
Xy_Yes_No_md.to_csv('data/Xy_Yes_No_md.csv', index=False)

In [12]:
# compare 

Xy_Yes_No.compare(Xy_Yes_No_md, keep_shape=True, keep_equal=True)

   Age_at_Surgery       Race       Surgery       Smoker          BMI  \
             self other self other    self other   self other   self
0            77.0  77.0  1.0   1.0     1.0   1.0    0.0   0.0  23.17
1            81.0  81.0  1.0   1.0     2.0   2.0    1.0   1.0  28.58
2            84.0  84.0  1.0   1.0     1.0   1.0    0.0   0.0  28.11
3            70.0  70.0  1.0   1.0     1.0   1.0    0.0   0.0  28.10
4            45.0  45.0  1.0   1.0     2.0   2.0    0.0   0.0  22.11
5            58.0  58.0  5.0   5.0     1.0   1.0    1.0   1.0  25.96
6            78.0  78.0  1.0   1.0     1.0   1.0    0.0   0.0  26.50
7            73.0  73.0  1.0   1.0     1.0   1.0    1.0   1.0  33.95
8            69.0  69.0  1.0   1.0     1.0   1.0    1.0   1.0  34.21
9            73.0  73.0  1.0   1.0     1.0   1.0    1.0   1.0  26.61
10           65.0  65.0  1.0   1.0     1.0   1.0    1.0   1.0  36.80
11           64.0  64.0  1.0   1.0     1.0   1.0    2.0   2.0  20.36
12           68.0  68.0  1.0   1.0     1.0   1.0    1.0   1.0  21.05
13           51.0  51.0  1.0   1.0     1.0   1.0    2.0   2.0  32.09
14           73.0  73.0  1.0   1.0     1.0   1.0    3.0   3.0  22.97
15           76.0  76.0  1.0   1.0     1.0   1.0    1.0   1.0  30.52
16           65.0  65.0  1.0   1.0     2.0   2.0    3.0   3.0  52.02
17           75.0  75.0  1.0   1.0     1.0   1.0    0.0   0.0  28.35
18           59.0  59.0  1.0   1.0     2.0   2.0    1.0   1.0  25.06
19           47.0  47.0  2.0   2.0     1.0   1.0    3.0   3.0  22.53
20           79.0  79.0  1.0   1.0     2.0   2.0    1.0   1.0  23.76
21           76.0  76.0  1.0   1.0     1.0   1.0    3.0   3.0  26.57
22           73.0  73.0  1.0   1.0     2.0   2.0    0.0   0.0    NaN
23           45.0  45.0  1.0   1.0     2.0   2.0    1.0   1.0  52.12
24           76.0  76.0  1.0   1.0     1.0   1.0    1.0   1.0  24.41
25           61.0  61.0  1.0   1.0     2.0   2.0    0.0   0.0  27.45
26           60.0  60.0  1.0   1.0     1.0   1.0    1.0   1.0  26.37
27           50.0  50.0  1.0   1.0     1.0   1.0    2.0   2.0  28.95
28           61.0  61.0  1.0   1.0     2.0   2.0    1.0   1.0  30.21
29           60.0  60.0  1.0   1.0     1.0   1.0    2.0   2.0  24.10
30           54.0  54.0  1.0   1.0     2.0   2.0    3.0   3.0  33.58
31           77.0  77.0  1.0   1.0     1.0   1.0    1.0   1.0  43.91
32           75.0  75.0  1.0   1.0     1.0   1.0    1.0   1.0  27.99
33           52.0  52.0  2.0   2.0     1.0   1.0    2.0   2.0  20.84
34           68.0  68.0  1.0   1.0     1.0   1.0    0.0   0.0  21.32
35           72.0  72.0  1.0   1.0     2.0   2.0    1.0   1.0  32.73
36           69.0  69.0  1.0   1.0     2.0   2.0    2.0   2.0  24.13
37           28.0  28.0  1.0   1.0     1.0   1.0    0.0   0.0  17.78
38           64.0  64.0  1.0   1.0     1.0   1.0    2.0   2.0    NaN
39           75.0  75.0  1.0   1.0     2.0   2.0    0.0   0.0  28.50
40           57.0  57.0  1.0   1.0     1.0   1.0    1.0   1.0  33.76
41           64.0  64.0  1.0   1.0     1.0   1.0    1.0   1.0  28.96
42           60.0  60.0  1.0   1.0     2.0   2.0    1.0   1.0   4.89
43           69.0  69.0  1.0   1.0     1.0   1.0    1.0   1.0  33.27
44           74.0  74.0  1.0   1.0     1.0   1.0    1.0   1.0  43.10
45           71.0  71.0  1.0   1.0     2.0   2.0    2.0   2.0  39.77
46           64.0  64.0  1.0   1.0     1.0   1.0    2.0   2.0  38.37
47           84.0  84.0  1.0   1.0     1.0   1.0    1.0   1.0  24.38
48           70.0  70.0  1.0   1.0     1.0   1.0    1.0   1.0  36.62
49           63.0  63.0  1.0   1.0     1.0   1.0    0.0   0.0  34.73
50           87.0  87.0  1.0   1.0     2.0   2.0    2.0   2.0  22.75
51           63.0  63.0  1.0   1.0     1.0   1.0    1.0   1.0  22.69
52           79.0  79.0  1.0   1.0     2.0   2.0    1.0   1.0  27.73
53           63.0  63.0  1.0   1.0     1.0   1.0    1.0   1.0  29.94
54           77.0  77.0  1.0   1.0     2.0   2.0    1.0   1.0  25.56
55           57.0  57.0  1.0   1.0     1.0   1.0    1.0   1.0  31.86
56           90.0  90.0  1.0   1.0     1.0   1.0    3.0   3.0  25.82
57           71.0  71.0  1.0   1.0     1.0   1.0    1.0   1.0  20.19
58           76.0  76.0  1.0   1.0     1.0   1.0    3.0   3.0  31.86
59           36.0  36.0  1.0   1.0     1.0   1.0    1.0   1.0  45.59
60           60.0  60.0  1.0   1.0     2.0   2.0    2.0   2.0  30.77
61           76.0  76.0  1.0   1.0     2.0   2.0    3.0   3.0  32.20
62           71.0  71.0  1.0   1.0     1.0   1.0    0.0   0.0  40.64
63           69.0  69.0  1.0   1.0     2.0   2.0    0.0   0.0  25.99
64           81.0  81.0  1.0   1.0     2.0   2.0    1.0   1.0  28.74
65           67.0  67.0  1.0   1.0     1.0   1.0    1.0   1.0  36.76
66           79.0  79.0  1.0   1.0     1.0   1.0    1.0   1.0  39.58
67           79.0  79.0  1.0   1.0     1.0   1.0    1.0   1.0  21.89
68           88.0  88.0  1.0   1.0     1.0   1.0    1.0   1.0    NaN
69           62.0  62.0  1.0   1.0     1.0   1.0    1.0   1.0  24.91
70           76.0  76.0  1.0   1.0     1.0   1.0    0.0   0.0  33.36
71           55.0  55.0  1.0   1.0     1.0   1.0    1.0   1.0  26.60
72           77.0  77.0  1.0   1.0     2.0   2.0    1.0   1.0  26.17
73           91.0  91.0  1.0   1.0     1.0   1.0    0.0   0.0  19.22

               NAC          cT          pT       cT_or_pT         pN        \
        other self other  self other  self other     self other self other
0   23.170000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
1   28.580000  NaN   0.0   1.0   1.0   NaN   1.0      1.0   1.0  NaN   1.0
2   28.110000  0.0   0.0   NaN   4.0   9.0   9.0      9.0   9.0  4.0   4.0
3   28.100000  0.0   0.0   4.0   4.0   8.0   8.0      8.0   8.0  0.0   0.0
4   22.110000  NaN   0.0   2.0   2.0   NaN   3.0      2.0   2.0  NaN   4.0
5   25.960000  1.0   1.0   4.0   4.0  11.0  11.0      4.0   4.0  1.0   1.0
6   26.500000  1.0   1.0   4.0   4.0  11.0  11.0     11.0  11.0  0.0   0.0
7   33.950000  0.0   0.0   4.0   4.0   5.0   5.0      4.0   4.0  1.0   1.0
8   34.210000  0.0   0.0   4.0   4.0   3.0   3.0      4.0   4.0  0.0   0.0
9   26.610000  1.0   1.0  10.0  10.0  11.0  11.0     10.0  10.0  0.0   0.0
10  36.800000  1.0   1.0   4.0   4.0   8.0   8.0      8.0   8.0  0.0   0.0
11  20.360000  0.0   0.0   7.0   7.0  11.0  11.0      7.0   7.0  3.0   3.0
12  21.050000  1.0   1.0   4.0   4.0   6.0   6.0      4.0   4.0  0.0   0.0
13  32.090000  1.0   1.0   7.0   7.0   6.0   6.0      7.0   7.0  0.0   0.0
14  22.970000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
15  30.520000  0.0   0.0   7.0   7.0   6.0   6.0      7.0   7.0  0.0   0.0
16  52.020000  0.0   0.0   1.0   1.0   NaN   1.0      1.0   1.0  NaN   0.0
17  28.350000  1.0   1.0   7.0   7.0   8.0   8.0      8.0   8.0  0.0   0.0
18  25.060000  0.0   0.0   7.0   7.0   NaN   6.0      7.0   7.0  NaN   0.0
19  22.530000  1.0   1.0   NaN  10.0   9.0   9.0      9.0   9.0  1.0   1.0
20  23.760000  0.0   0.0   3.0   3.0   1.0   1.0      3.0   3.0  NaN   1.0
21  26.570000  0.0   0.0   6.0   6.0   8.0   8.0      8.0   8.0  2.0   2.0
22  34.688695  0.0   0.0   1.0   1.0   3.0   3.0      1.0   1.0  NaN   0.0
23  52.120000  0.0   0.0   1.0   1.0   NaN  11.0      1.0   1.0  NaN   0.0
24  24.410000  0.0   0.0   4.0   4.0   6.0   6.0      4.0   4.0  0.0   0.0
25  27.450000  0.0   0.0   4.0   4.0   NaN   9.0      4.0   4.0  NaN   0.0
26  26.370000  1.0   1.0  10.0  10.0   9.0   9.0     10.0  10.0  0.0   0.0
27  28.950000  1.0   1.0   NaN   7.0   9.0   9.0      9.0   9.0  0.0   0.0
28  30.210000  0.0   0.0   2.0   2.0   NaN   8.0      2.0   2.0  NaN   0.0
29  24.100000  0.0   0.0   3.0   3.0   9.0   9.0      3.0   3.0  1.0   1.0
30  33.580000  0.0   0.0   1.0   1.0   NaN   1.0      1.0   1.0  NaN   0.0
31  43.910000  0.0   0.0   1.0   1.0  11.0  11.0     11.0  11.0  0.0   0.0
32  27.990000  1.0   1.0   4.0   4.0   9.0   9.0      4.0   4.0  3.0   3.0
33  20.840000  1.0   1.0  10.0  10.0  11.0  11.0     11.0  11.0  0.0   0.0
34  21.320000  1.0   1.0   7.0   7.0  11.0  11.0      7.0   7.0  0.0   0.0
35  32.730000  0.0   0.0   3.0   3.0   5.0   5.0      5.0   5.0  NaN   0.0
36  24.130000  0.0   0.0   3.0   3.0   NaN   9.0      3.0   3.0  NaN   0.0
37  17.780000  1.0   1.0   NaN  10.0  11.0  11.0     11.0  11.0  2.0   2.0
38  21.051999  1.0   1.0   4.0   4.0  11.0  11.0     11.0  11.0  0.0   0.0
39  28.500000  0.0   0.0   3.0   3.0   3.0   3.0      3.0   3.0  NaN   0.0
40  33.760000  0.0   0.0   4.0   4.0   9.0   9.0      4.0   4.0  3.0   3.0
41  28.960000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
42   4.890000  0.0   0.0   3.0   3.0   NaN   6.0      3.0   3.0  NaN   0.0
43  33.270000  1.0   1.0   4.0   4.0   0.0   0.0      4.0   4.0  0.0   0.0
44  43.100000  0.0   0.0   NaN  10.0   1.0   1.0      1.0   1.0  0.0   0.0
45  39.770000  0.0   0.0   1.0   1.0   NaN   3.0      1.0   1.0  NaN   1.0
46  38.370000  1.0   1.0   4.0   4.0   6.0   6.0      6.0   6.0  0.0   0.0
47  24.380000  0.0   0.0   4.0   4.0  12.0  12.0     12.0  12.0  1.0   1.0
48  36.620000  1.0   1.0   4.0   4.0   6.0   6.0      6.0   6.0  0.0   0.0
49  34.730000  1.0   1.0   4.0   4.0   0.0   0.0      4.0   4.0  0.0   0.0
50  22.750000  0.0   0.0   3.0   3.0   1.0   1.0      3.0   3.0  NaN   0.0
51  22.690000  1.0   1.0   7.0   7.0   1.0   1.0      7.0   7.0  0.0   0.0
52  27.730000  0.0   0.0   4.0   4.0   NaN   9.0      4.0   4.0  NaN   0.0
53  29.940000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
54  25.560000  0.0   0.0   1.0   1.0   NaN   9.0      1.0   1.0  NaN   0.0
55  31.860000  0.0   0.0   1.0   1.0   1.0   1.0      1.0   1.0  0.0   0.0
56  25.820000  1.0   1.0   3.0   3.0   9.0   9.0      9.0   9.0  4.0   4.0
57  20.190000  1.0   1.0   4.0   4.0   8.0   8.0      4.0   4.0  3.0   3.0
58  31.860000  0.0   0.0   3.0   3.0   9.0   9.0      9.0   9.0  0.0   0.0
59  45.590000  0.0   0.0   3.0   3.0   3.0   3.0      3.0   3.0  0.0   0.0
60  30.770000  1.0   1.0   4.0   4.0   5.0   5.0      4.0   4.0  NaN   0.0
61  32.200000  0.0   0.0   3.0   3.0   4.0   4.0      4.0   4.0  NaN   0.0
62  40.640000  1.0   1.0   NaN   7.0   5.0   5.0      5.0   5.0  0.0   0.0
63  25.990000  0.0   0.0   3.0   3.0   1.0   1.0      3.0   3.0  NaN   0.0
64  28.740000  0.0   0.0   1.0   1.0   NaN   9.0      1.0   1.0  NaN   0.0
65  36.760000  1.0   1.0   4.0   4.0   6.0   6.0      6.0   6.0  2.0   2.0
66  39.580000  0.0   0.0   7.0   7.0  11.0  11.0     11.0  11.0  0.0   0.0
67  21.890000  0.0   0.0   7.0   7.0   9.0   9.0      9.0   9.0  0.0   0.0
68  35.336983  1.0   1.0  10.0  10.0   9.0   9.0     10.0  10.0  0.0   0.0
69  24.910000  1.0   1.0   4.0   4.0  11.0  11.0      4.0   4.0  1.0   1.0
70  33.360000  0.0   0.0   4.0   4.0   6.0   6.0      6.0   6.0  0.0   0.0
71  26.600000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  2.0   2.0
72  26.170000  0.0   0.0   1.0   1.0   NaN   1.0      1.0   1.0  NaN   0.0
73  19.220000  0.0   0.0   4.0   4.0   5.0   5.0      4.0   4.0  3.0   3.0

   Bx_Histology       Histology       Sample_weight_g_tumor          \
           self other      self other                  self   other
0           1.0   1.0       1.0   1.0                 0.840   0.840
1           1.0   1.0      11.0  11.0                 0.180   0.180
2           4.0   4.0       6.0   6.0                 0.070   0.070
3           1.0   1.0       4.0   4.0                 3.570   3.570
4           1.0   1.0       1.0   1.0                 1.310   1.310
5           6.0   6.0       6.0   6.0                 0.600   0.600
6           1.0   1.0       1.0   1.0                 0.710   0.710
7           1.0   1.0       1.0   1.0                 0.000   0.000
8           1.0   1.0       1.0   1.0                 1.300   1.300
9           4.0   4.0       1.0   1.0                 3.030   3.030
10          1.0   1.0       4.0   4.0                 1.640   1.640
11          1.0   1.0       1.0   1.0                 1.380   1.380
12          1.0   1.0       1.0   1.0                 1.660   1.660
13          4.0   4.0       4.0   4.0                 0.810   0.810
14          1.0   1.0       1.0   1.0                 0.610   0.610
15          5.0   5.0       1.0   1.0                 0.000   0.000
16          1.0   1.0       1.0   1.0                 0.230   0.230
17          1.0   1.0       1.0   1.0                 0.000   0.000
18          1.0   1.0       1.0   1.0                 5.210   5.210
19          1.0   1.0       1.0   1.0                 0.000   0.000
20          1.0   1.0       1.0   1.0                 0.290   0.290
21         11.0  11.0       7.0   7.0                 0.490   0.490
22          1.0   1.0       1.0   1.0                 0.000   0.000
23          NaN   1.0       NaN   1.0                 0.070   0.070
24          1.0   1.0       1.0   1.0                 0.540   0.540
25          1.0   1.0       1.0   1.0                 0.000   0.000
26          4.0   4.0       4.0   4.0                 1.120   1.120
27          4.0   4.0       7.0   7.0                 0.200   0.200
28          1.0   1.0       1.0   1.0                 0.340   0.340
29          1.0   1.0       4.0   4.0                 0.000   0.000
30          1.0   1.0       1.0   1.0                 0.548   0.548
31          1.0   1.0       1.0   1.0                 0.000   0.000
32          1.0   1.0       1.0   1.0                 0.000   0.000
33          1.0   1.0      12.0  12.0                 5.060   5.060
34          1.0   1.0       2.0   2.0                 0.340   0.340
35          1.0   1.0       1.0   1.0                 1.000   1.000
36          1.0   1.0       1.0   1.0                 0.000   0.000
37          2.0   2.0       2.0   2.0                 0.400   0.400
38          1.0   1.0      10.0  10.0                 0.830   0.830
39          NaN   1.0       1.0   1.0                 0.340   0.340
40         10.0  10.0      10.0  10.0                 0.460   0.460
41          2.0   2.0       4.0   4.0                10.950  10.950
42          1.0   1.0       1.0   1.0                 0.000   0.000
43          8.0   8.0       NaN   1.0                 0.610   0.610
44          1.0   1.0       1.0   1.0                 1.010   1.010
45          1.0   1.0       1.0   1.0                 0.562   0.562
46          1.0   1.0       1.0   1.0                 0.190   0.190
47          1.0   1.0       4.0   4.0                 4.110   4.110
48          6.0   6.0       4.0   4.0                 2.790   2.790
49          1.0   1.0       0.0   0.0                 1.340   1.340
50          1.0   1.0       1.0   1.0                 0.460   0.460
51          1.0   1.0       1.0   1.0                 0.000   0.000
52          1.0   1.0       1.0   1.0                 2.270   2.270
53          1.0   1.0       7.0   7.0                 0.130   0.130
54          1.0   1.0       1.0   1.0                 0.000   0.000
55          1.0   1.0       1.0   1.0                 2.400   2.400
56          1.0   1.0       1.0   1.0                 0.930   0.930
57          1.0   1.0       1.0   1.0                 0.000   0.000
58          5.0   5.0       1.0   1.0                 0.540   0.540
59          1.0   1.0       1.0   1.0                 0.970   0.970
60          1.0   1.0      13.0  13.0                 0.000   0.000
61          1.0   1.0       1.0   1.0                 0.560   0.560
62          1.0   1.0       1.0   1.0                 0.000   0.000
63          1.0   1.0       1.0   1.0                 0.000   0.000
64          1.0   1.0       1.0   1.0                 0.000   0.000
65          1.0   1.0       5.0   5.0                 0.870   0.870
66          9.0   9.0      10.0  10.0                 2.340   2.340
67          1.0   1.0       6.0   6.0                 1.480   1.480
68          1.0   1.0       1.0   1.0                 0.480   0.480
69          1.0   1.0      10.0  10.0                 0.180   0.180
70          4.0   4.0       1.0   1.0                 0.570   0.570
71          4.0   4.0       1.0   1.0                 0.490   0.490
72          1.0   1.0       1.0   1.0                 0.670   0.670
73          1.0   1.0       1.0   1.0                 0.710   0.710

   Tumor_digest_count_primary_tumor               \
                               self        other
0                         3020000.0    3020000.0
1                         1420000.0    1420000.0
2                          350000.0     350000.0
3                        55000000.0   55000000.0
4                         7160000.0    7160000.0
5                         2500000.0    2500000.0
6                         2200000.0    2200000.0
7                         2000000.0    2000000.0
8                         2800000.0    2800000.0
9                        26000000.0   26000000.0
10                       90000000.0   90000000.0
11                        4250000.0    4250000.0
12                       60000000.0   60000000.0
13                        1190000.0    1190000.0
14                        1650000.0    1650000.0
15                        3000000.0    3000000.0
16                              0.0          0.0
17                        1000000.0    1000000.0
18                       23200000.0   23200000.0
19                              0.0          0.0
20                        8400000.0    8400000.0
21                        1120000.0    1120000.0
22                              0.0          0.0
23                              0.0          0.0
24                        2500000.0    2500000.0
25                              0.0          0.0
26                        1400000.0    1400000.0
27                         200000.0     200000.0
28                         150000.0     150000.0
29                        3500000.0    3500000.0
30                              0.0          0.0
31                              0.0          0.0
32                        1560000.0    1560000.0
33                       33600000.0   33600000.0
34                         465000.0     465000.0
35                        1000000.0    1000000.0
36                              0.0          0.0
37                        1300000.0    1300000.0
38                        2400000.0    2400000.0
39                        3000000.0    3000000.0
40                        5000000.0    5000000.0
41                       95700000.0   95700000.0
42                              0.0          0.0
43                         570000.0     570000.0
44                       27600000.0   27600000.0
45                              0.0          0.0
46                          84000.0      84000.0
47                       15100000.0   15100000.0
48                      100000000.0  100000000.0
49                        1000000.0    1000000.0
50                        5000000.0    5000000.0
51                       40200000.0   40200000.0
52                        9900000.0    9900000.0
53                        1200000.0    1200000.0
54                              0.0          0.0
55                      255000000.0  255000000.0
56                        2500000.0    2500000.0
57                         210000.0     210000.0
58                        7400000.0    7400000.0
59                       14000000.0   14000000.0
60                        1500000.0    1500000.0
61                       14500000.0   14500000.0
62                              0.0          0.0
63                        2000000.0    2000000.0
64                              0.0          0.0
65                         200000.0     200000.0
66                        1750000.0    1750000.0
67                       11500000.0   11500000.0
68                        8900000.0    8900000.0
69                        1170000.0    1170000.0
70                       31000000.0   31000000.0
71                       31500000.0   31500000.0
72                          64000.0      64000.0
73                        1300000.0    1300000.0

   Number_of_fragments_plated_tumor       OverallTILGrowth
                               self other             self other