In [1]:
# load libraies

%run py_libraries.py

/Users/4476224/.local/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.6.0 and strictly below 2.9.0 (nightly versions are not supported).
 The versions of TensorFlow you are currently using is 2.13.0 and is not supported.
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(

WARNING:tensorflow:From /opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [2]:
# loading utility files

from utility.sv_fig import savefig
from utility.make_cm import make_confusion_matrix
from utility.get_g_result import get_gamma_results
from utility.plt_result import plot_results

In [3]:
def savefig(filename, crop = True):
    plt.savefig('{}.pdf'.format(filename))

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_row', None)

# load data
X_train = pd.read_csv('data/norm_X_train_Yes_No.csv')
X_test = pd.read_csv('data/norm_X_test_Yes_No.csv')
y_train = pd.read_csv('data/y_train_Yes_No.csv')
y_test = pd.read_csv('data/y_test_Yes_No.csv')


print(X_test.shape)

(32, 15)

In [5]:
# Print the column names as a list
print(X_test.columns.tolist())

['Age_at_Surgery', 'Race', 'Surgery', 'Smoker', 'BMI', 'NAC', 'cT', 'pT', 'cT_or_pT', 'pN', 'Bx_Histology', 'Histology', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor', 'Number_of_fragments_plated_tumor']

In [6]:
Xy_Yes_No = pd.concat([X_test, y_test], axis=1)

In [7]:
# checking number of patients not missing data

ndata_f_noMiss = Xy_Yes_No.copy()
num_complete_rows = ndata_f_noMiss.dropna().shape[0]
print(num_complete_rows)

18

In [7]:
#
col_to_scale = ['Age_at_Surgery', 'BMI', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor',]

def midas_impl(missing, col_to_scale, n_epoch):
    missing_cp = missing.copy() # make copy of missing df
    
    # scaler = MinMaxScaler().fit(missing_cp[col_to_scale]) # scale data
    scaler = StandardScaler().fit(missing_cp[col_to_scale]) # scale data
    missing_sc = scaler.transform(missing_cp[col_to_scale]) # this is an array, convert to df
    # missing_sc = missing_cp.copy()

    missing_df = pd.DataFrame({'Age_at_Surgery':missing_sc[:,0],
                               'BMI':missing_sc[:,1],
                               'Sample_weight_g_tumor':missing_sc[:,2],
                               'Tumor_digest_count_primary_tumor':missing_sc[:,3],
                               })
    
    # Extract cat columns from missing
    ext_col1 = missing_cp['Race']
    ext_col2 = missing_cp['Surgery']
    ext_col3 = missing_cp['Smoker']
    ext_col4 = missing_cp['NAC']
    ext_col5 = missing_cp['cT']
    ext_col6 = missing_cp['pT']
    ext_col7 = missing_cp['cT_or_pT']
    ext_col8 = missing_cp['pN']
    ext_col9 = missing_cp['Bx_Histology']
    ext_col10 = missing_cp['Histology']
    ext_col11 = missing_cp['Number_of_fragments_plated_tumor']
    ext_col12 = missing_cp['OverallTILGrowth']
    

    # Add the extracted cat columns to missing_df
    missing_df = pd.concat([missing_df, ext_col1.rename('Race')], axis=1)
    missing_df = pd.concat([missing_df, ext_col2.rename('Surgery')], axis=1)
    missing_df = pd.concat([missing_df, ext_col3.rename('Smoker')], axis=1)
    missing_df = pd.concat([missing_df, ext_col4.rename('NAC')], axis=1)
    missing_df = pd.concat([missing_df, ext_col5.rename('cT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col6.rename('pT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col7.rename('cT_or_pT')], axis=1)
    missing_df = pd.concat([missing_df, ext_col8.rename('pN')], axis=1)
    missing_df = pd.concat([missing_df, ext_col9.rename('Bx_Histology')], axis=1)
    missing_df = pd.concat([missing_df, ext_col10.rename('Histology')], axis=1)
    missing_df = pd.concat([missing_df, ext_col11.rename('Number_of_fragments_plated_tumor')], axis=1)
    missing_df = pd.concat([missing_df, ext_col12.rename('OverallTILGrowth')], axis=1)
    

    missing_df.to_csv('missing_test.csv')
    data_0 = pd.read_csv('missing_test.csv')
    data_0.columns.str.strip()

    categorical = ['Race','Surgery','Smoker','NAC','cT','pT','cT_or_pT','pN','Bx_Histology','Histology','Number_of_fragments_plated_tumor','OverallTILGrowth']
    
    data_cat, cat_cols_list = md.cat_conv(data_0[categorical])

    data_0.drop(categorical, axis = 1, inplace = True)
    constructor_list = [data_0]
    constructor_list.append(data_cat)
    data_in = pd.concat(constructor_list, axis=1)

    na_loc = data_in.isnull()
    data_in[na_loc] = np.nan

    # imputer = md.Midas(layer_structure = [128,128], vae_layer = True, seed = 89, input_drop = 0.75, learn_rate = 0.0001)
    imputer = md.Midas(layer_structure = [128,128], vae_layer = False, seed = 42, input_drop = 0.75, learn_rate = 0.001)
    imputer.build_model(data_in, softmax_columns = cat_cols_list)
    imputer.train_model(training_epochs = n_epoch)

    # do not update M
    imputations = imputer.generate_samples(m=20).output_list

    flat_cats = [cat for variable in cat_cols_list for cat in variable]
    for i in range(len(imputations)):
        tmp_cat = [imputations[i][x].idxmax(axis=1) for x in cat_cols_list]
        cat_df = pd.DataFrame({categorical[i]:tmp_cat[i] for i in range(len(categorical))})
        imputations[i] = pd.concat([imputations[i], cat_df], axis = 1).drop(flat_cats, axis = 1)

    # Implementing an efficient way to replace 'Column_name_Num' with Num in every data_item whose column is 'Column_name'    
    # Loop through all imputations
    for i in range(len(imputations)):
        df = imputations[i]
        
        # Process each column independently
        for col in df.columns:
            
            # Only operate on string/object columns
            if df[col].dtype == 'object':
                # Pattern: match "ColumnName_Number"
                pattern = rf'^{re.escape(col)}_(.+)$'
                # pattern = rf'^{re.escape(col)}_(\d+)$'
                
                df[col] = df[col].str.replace(
                    pattern,
                    r'\1',
                    regex=True
                )
                
        # Optional: convert to numeric if desired
        df = df.apply(pd.to_numeric, errors='ignore')
        imputations[i] = df

    # rescale imputations
    imputations[0][col_to_scale] = scaler.inverse_transform(imputations[0][col_to_scale])
    imputations[1][col_to_scale] = scaler.inverse_transform(imputations[1][col_to_scale])
    imputations[2][col_to_scale] = scaler.inverse_transform(imputations[2][col_to_scale])
    imputations[3][col_to_scale] = scaler.inverse_transform(imputations[3][col_to_scale])
    imputations[4][col_to_scale] = scaler.inverse_transform(imputations[4][col_to_scale])
    imputations[5][col_to_scale] = scaler.inverse_transform(imputations[5][col_to_scale])
    imputations[6][col_to_scale] = scaler.inverse_transform(imputations[6][col_to_scale])
    imputations[7][col_to_scale] = scaler.inverse_transform(imputations[7][col_to_scale])
    imputations[8][col_to_scale] = scaler.inverse_transform(imputations[8][col_to_scale])
    imputations[9][col_to_scale] = scaler.inverse_transform(imputations[9][col_to_scale])
    imputations[10][col_to_scale] = scaler.inverse_transform(imputations[10][col_to_scale])
    imputations[11][col_to_scale] = scaler.inverse_transform(imputations[11][col_to_scale])
    imputations[12][col_to_scale] = scaler.inverse_transform(imputations[12][col_to_scale])
    imputations[13][col_to_scale] = scaler.inverse_transform(imputations[13][col_to_scale])
    imputations[14][col_to_scale] = scaler.inverse_transform(imputations[14][col_to_scale])
    imputations[15][col_to_scale] = scaler.inverse_transform(imputations[15][col_to_scale])
    imputations[16][col_to_scale] = scaler.inverse_transform(imputations[16][col_to_scale])
    imputations[17][col_to_scale] = scaler.inverse_transform(imputations[17][col_to_scale])
    imputations[18][col_to_scale] = scaler.inverse_transform(imputations[18][col_to_scale])
    imputations[19][col_to_scale] = scaler.inverse_transform(imputations[19][col_to_scale])

    n=0
    for i in imputations:
        file_out_csv = "midas_test/midas_test_" + str(n) + ".csv"
        i.to_csv(file_out_csv, index=False)
        n += 1

    df0 = pd.read_csv('midas_test/midas_test_0.csv'); df0 = df0.iloc[:,1:]
    df1 = pd.read_csv('midas_test/midas_test_1.csv'); df1 = df1.iloc[:,1:]
    df2 = pd.read_csv('midas_test/midas_test_2.csv'); df2 = df2.iloc[:,1:]
    df3 = pd.read_csv('midas_test/midas_test_3.csv'); df3 = df3.iloc[:,1:]
    df4 = pd.read_csv('midas_test/midas_test_4.csv'); df4 = df4.iloc[:,1:]
    df5 = pd.read_csv('midas_test/midas_test_5.csv'); df5 = df5.iloc[:,1:]
    df6 = pd.read_csv('midas_test/midas_test_6.csv'); df6 = df6.iloc[:,1:]
    df7 = pd.read_csv('midas_test/midas_test_7.csv'); df7 = df7.iloc[:,1:]
    df8 = pd.read_csv('midas_test/midas_test_8.csv'); df8 = df8.iloc[:,1:]
    df9 = pd.read_csv('midas_test/midas_test_9.csv'); df9 = df9.iloc[:,1:]
    df10 = pd.read_csv('midas_test/midas_test_10.csv'); df10 = df10.iloc[:,1:]
    df11 = pd.read_csv('midas_test/midas_test_11.csv'); df11 = df11.iloc[:,1:]
    df12 = pd.read_csv('midas_test/midas_test_12.csv'); df12 = df12.iloc[:,1:]
    df13 = pd.read_csv('midas_test/midas_test_13.csv'); df13 = df13.iloc[:,1:]
    df14 = pd.read_csv('midas_test/midas_test_14.csv'); df14 = df14.iloc[:,1:]
    df15 = pd.read_csv('midas_test/midas_test_15.csv'); df15 = df15.iloc[:,1:]
    df16 = pd.read_csv('midas_test/midas_test_16.csv'); df16 = df16.iloc[:,1:]
    df17 = pd.read_csv('midas_test/midas_test_17.csv'); df17 = df17.iloc[:,1:]
    df18 = pd.read_csv('midas_test/midas_test_18.csv'); df18 = df18.iloc[:,1:]
    df19 = pd.read_csv('midas_test/midas_test_19.csv'); df19 = df19.iloc[:,1:]

    # Initialize the output dataframe with the same dimensions
    output_df = pd.DataFrame(index=df0.index, columns=df0.columns)

    # Process continuous columns
    for col in df1.columns[:4]:
        output_df[col] = (abs(df0[col]) + abs(df1[col]) + abs(df2[col]) + abs(df3[col]) + abs(df4[col]) + 
                          abs(df5[col]) + abs(df6[col]) + abs(df7[col]) + abs(df8[col]) + abs(df9[col]) + 
                         abs(df10[col]) + abs(df11[col]) + abs(df12[col]) + abs(df13[col]) + abs(df14[col]) + 
                          abs(df15[col]) + abs(df16[col]) + abs(df17[col]) + abs(df18[col]) + abs(df19[col])) / 20

    # Process categorical columns
    for col in df1.columns[4:]:
        output_df[col] = pd.concat([df0[col],df1[col],df2[col],df3[col],df4[col],df5[col],df6[col],df7[col],df8[col],df9[col],
                                   df10[col],df11[col],df12[col],df13[col],df14[col],df15[col],df16[col],df17[col],df18[col],df19[col]], axis=1).median(axis=1)

    # Write the output dataframe to a CSV file
    output_df.to_csv('output_test.csv', index=False)

    # re-order cols in output_df
    output_df_re = output_df[['Age_at_Surgery', 'Race', 'Surgery', 'Smoker', 'BMI', 'NAC', 'cT', 'pT', 'cT_or_pT', 'pN', 
                              'Bx_Histology', 'Histology', 'Sample_weight_g_tumor', 'Tumor_digest_count_primary_tumor', 
                              'Number_of_fragments_plated_tumor','OverallTILGrowth']].copy()
    return output_df_re

In [8]:
# calculate proportion of missingness in ndata_noR

# total num of NaN in the ndata_noR
total_nan_count = X_test.isna().sum().sum()

# total num of cells in ndata_noR
total_cells = X_test.size

# proportion of NaN
NaN_proportion = total_nan_count / total_cells

print('NaN_proportions:',NaN_proportion)

NaN_proportions: 0.04583333333333333

In [9]:
# 1.35% missingness

Xy_Yes_No_md = midas_impl(Xy_Yes_No, col_to_scale, 250)

Size index: [5, 3, 2, 4, 2, 6, 10, 11, 4, 4, 5, 12, 2]

Computation graph constructed

Metal device set to: Apple M1 Pro
Model initialised

Epoch: 0 , loss: 40.60445976257324
Epoch: 1 , loss: 79.321044921875
Epoch: 2 , loss: 113.20489120483398
Epoch: 3 , loss: 107.45294189453125
Epoch: 4 , loss: 71.3995590209961
Epoch: 5 , loss: 62.53718185424805
Epoch: 6 , loss: 64.57382202148438
Epoch: 7 , loss: 50.14341163635254
Epoch: 8 , loss: 42.63375282287598
Epoch: 9 , loss: 41.69715690612793
Epoch: 10 , loss: 39.88266372680664
Epoch: 11 , loss: 44.27877616882324
Epoch: 12 , loss: 35.453474044799805
Epoch: 13 , loss: 40.044307708740234
Epoch: 14 , loss: 38.9892578125
Epoch: 15 , loss: 37.579400062561035
Epoch: 16 , loss: 38.280717849731445
Epoch: 17 , loss: 39.939788818359375
Epoch: 18 , loss: 34.82228660583496
Epoch: 19 , loss: 36.479814529418945
Epoch: 20 , loss: 32.48378372192383
Epoch: 21 , loss: 37.84461784362793
Epoch: 22 , loss: 38.162864685058594
Epoch: 23 , loss: 33.08389091491699
Epoch: 24 , loss: 38.67002487182617
Epoch: 25 , loss: 42.31271743774414
Epoch: 26 , loss: 40.33522415161133
Epoch: 27 , loss: 35.954965591430664
Epoch: 28 , loss: 39.476308822631836
Epoch: 29 , loss: 38.584373474121094
Epoch: 30 , loss: 38.26269721984863
Epoch: 31 , loss: 47.70152282714844
Epoch: 32 , loss: 46.7957878112793
Epoch: 33 , loss: 55.9807014465332
Epoch: 34 , loss: 50.14715385437012
Epoch: 35 , loss: 53.11643600463867
Epoch: 36 , loss: 39.28069496154785
Epoch: 37 , loss: 39.85433578491211
Epoch: 38 , loss: 43.66127967834473
Epoch: 39 , loss: 41.22926330566406
Epoch: 40 , loss: 41.70569038391113
Epoch: 41 , loss: 52.391584396362305
Epoch: 42 , loss: 54.61177444458008
Epoch: 43 , loss: 47.04343795776367
Epoch: 44 , loss: 45.83695411682129
Epoch: 45 , loss: 46.098236083984375
Epoch: 46 , loss: 44.01797676086426
Epoch: 47 , loss: 44.23429870605469
Epoch: 48 , loss: 41.78227996826172
Epoch: 49 , loss: 48.97707748413086
Epoch: 50 , loss: 139.14090728759766
Epoch: 51 , loss: 60.98134231567383
Epoch: 52 , loss: 74.75127220153809
Epoch: 53 , loss: 46.863929748535156
Epoch: 54 , loss: 71.1431941986084
Epoch: 55 , loss: 99.38308334350586
Epoch: 56 , loss: 53.334442138671875
Epoch: 57 , loss: 44.93694305419922
Epoch: 58 , loss: 46.89159393310547
Epoch: 59 , loss: 40.82194137573242
Epoch: 60 , loss: 44.23272132873535
Epoch: 61 , loss: 42.35347938537598
Epoch: 62 , loss: 47.96420860290527
Epoch: 63 , loss: 44.26513862609863
Epoch: 64 , loss: 49.987449645996094
Epoch: 65 , loss: 44.824119567871094
Epoch: 66 , loss: 44.28186798095703
Epoch: 67 , loss: 46.79908752441406
Epoch: 68 , loss: 52.44448471069336
Epoch: 69 , loss: 48.9650993347168
Epoch: 70 , loss: 44.50593566894531
Epoch: 71 , loss: 41.420555114746094
Epoch: 72 , loss: 43.3969669342041
Epoch: 73 , loss: 46.30474090576172
Epoch: 74 , loss: 44.6820182800293
Epoch: 75 , loss: 45.65049743652344
Epoch: 76 , loss: 45.09212303161621
Epoch: 77 , loss: 39.506853103637695
Epoch: 78 , loss: 47.85742950439453
Epoch: 79 , loss: 45.97697639465332
Epoch: 80 , loss: 45.425405502319336
Epoch: 81 , loss: 45.89601135253906
Epoch: 82 , loss: 43.78140830993652
Epoch: 83 , loss: 47.505422592163086
Epoch: 84 , loss: 43.24893760681152
Epoch: 85 , loss: 46.17816734313965
Epoch: 86 , loss: 47.2401008605957
Epoch: 87 , loss: 45.07678031921387
Epoch: 88 , loss: 45.55425834655762
Epoch: 89 , loss: 47.473880767822266
Epoch: 90 , loss: 41.724456787109375
Epoch: 91 , loss: 41.93213653564453
Epoch: 92 , loss: 45.11451721191406
Epoch: 93 , loss: 50.43486404418945
Epoch: 94 , loss: 41.00273132324219
Epoch: 95 , loss: 44.19329833984375
Epoch: 96 , loss: 46.05353546142578
Epoch: 97 , loss: 47.572431564331055
Epoch: 98 , loss: 45.57275390625
Epoch: 99 , loss: 45.113224029541016
Epoch: 100 , loss: 45.859018325805664
Epoch: 101 , loss: 53.69467544555664
Epoch: 102 , loss: 45.4506950378418
Epoch: 103 , loss: 45.335269927978516
Epoch: 104 , loss: 44.184810638427734
Epoch: 105 , loss: 51.061758041381836
Epoch: 106 , loss: 45.93776321411133
Epoch: 107 , loss: 47.95469284057617
Epoch: 108 , loss: 50.80013465881348
Epoch: 109 , loss: 48.97080993652344
Epoch: 110 , loss: 46.43048667907715
Epoch: 111 , loss: 45.3823184967041
Epoch: 112 , loss: 39.443918228149414
Epoch: 113 , loss: 43.6016788482666
Epoch: 114 , loss: 45.334930419921875
Epoch: 115 , loss: 48.47611427307129
Epoch: 116 , loss: 52.52235221862793
Epoch: 117 , loss: 42.626380920410156
Epoch: 118 , loss: 43.72037124633789
Epoch: 119 , loss: 46.33328628540039
Epoch: 120 , loss: 49.979881286621094
Epoch: 121 , loss: 42.62998962402344
Epoch: 122 , loss: 45.98779296875
Epoch: 123 , loss: 47.95838165283203
Epoch: 124 , loss: 63.73070526123047
Epoch: 125 , loss: 45.97874641418457
Epoch: 126 , loss: 46.32537269592285
Epoch: 127 , loss: 49.94595146179199
Epoch: 128 , loss: 57.042625427246094
Epoch: 129 , loss: 46.642086029052734
Epoch: 130 , loss: 47.26386833190918
Epoch: 131 , loss: 43.2797794342041
Epoch: 132 , loss: 48.31959342956543
Epoch: 133 , loss: 49.53174018859863
Epoch: 134 , loss: 46.46033477783203
Epoch: 135 , loss: 48.539236068725586
Epoch: 136 , loss: 47.169551849365234
Epoch: 137 , loss: 47.06085968017578
Epoch: 138 , loss: 48.61355209350586
Epoch: 139 , loss: 50.60312843322754
Epoch: 140 , loss: 50.081621170043945
Epoch: 141 , loss: 49.12293815612793
Epoch: 142 , loss: 44.48649215698242
Epoch: 143 , loss: 48.79426193237305
Epoch: 144 , loss: 53.9449348449707
Epoch: 145 , loss: 43.13946342468262
Epoch: 146 , loss: 52.97643280029297
Epoch: 147 , loss: 49.359418869018555
Epoch: 148 , loss: 44.384498596191406
Epoch: 149 , loss: 88.83287048339844
Epoch: 150 , loss: 44.006099700927734
Epoch: 151 , loss: 48.28520393371582
Epoch: 152 , loss: 48.11830139160156
Epoch: 153 , loss: 47.588191986083984
Epoch: 154 , loss: 51.05844688415527
Epoch: 155 , loss: 65.64260482788086
Epoch: 156 , loss: 51.611270904541016
Epoch: 157 , loss: 44.74734878540039
Epoch: 158 , loss: 41.47698402404785
Epoch: 159 , loss: 44.51566696166992
Epoch: 160 , loss: 44.12246322631836
Epoch: 161 , loss: 43.91124725341797
Epoch: 162 , loss: 52.071739196777344
Epoch: 163 , loss: 45.748634338378906
Epoch: 164 , loss: 44.09687423706055
Epoch: 165 , loss: 51.70001792907715
Epoch: 166 , loss: 43.766056060791016
Epoch: 167 , loss: 49.66995429992676
Epoch: 168 , loss: 43.48899459838867
Epoch: 169 , loss: 46.72490692138672
Epoch: 170 , loss: 52.366098403930664
Epoch: 171 , loss: 50.27877998352051
Epoch: 172 , loss: 43.789968490600586
Epoch: 173 , loss: 49.52839469909668
Epoch: 174 , loss: 46.56390571594238
Epoch: 175 , loss: 42.636606216430664
Epoch: 176 , loss: 44.97146797180176
Epoch: 177 , loss: 45.197418212890625
Epoch: 178 , loss: 42.87965774536133
Epoch: 179 , loss: 875.8146057128906
Epoch: 180 , loss: 9680.70458984375
Epoch: 181 , loss: 6490.447021484375
Epoch: 182 , loss: 1943.0289611816406
Epoch: 183 , loss: 315.0654754638672
Epoch: 184 , loss: 362.54859924316406
Epoch: 185 , loss: 239.79205322265625
Epoch: 186 , loss: 327.135986328125
Epoch: 187 , loss: 175.1222686767578
Epoch: 188 , loss: 175.66122436523438
Epoch: 189 , loss: 137.8157730102539
Epoch: 190 , loss: 137.4738006591797
Epoch: 191 , loss: 135.92407608032227
Epoch: 192 , loss: 111.81673812866211
Epoch: 193 , loss: 113.97445297241211
Epoch: 194 , loss: 97.38447952270508
Epoch: 195 , loss: 99.38243103027344
Epoch: 196 , loss: 92.7251205444336
Epoch: 197 , loss: 90.3780632019043
Epoch: 198 , loss: 76.43299865722656
Epoch: 199 , loss: 75.29379653930664
Epoch: 200 , loss: 74.29899215698242
Epoch: 201 , loss: 71.9007797241211
Epoch: 202 , loss: 84.81295013427734
Epoch: 203 , loss: 66.35694122314453
Epoch: 204 , loss: 74.3773307800293
Epoch: 205 , loss: 60.14301872253418
Epoch: 206 , loss: 73.749755859375
Epoch: 207 , loss: 65.98370170593262
Epoch: 208 , loss: 61.738624572753906
Epoch: 209 , loss: 58.53620910644531
Epoch: 210 , loss: 55.27890396118164
Epoch: 211 , loss: 58.04190444946289
Epoch: 212 , loss: 53.536529541015625
Epoch: 213 , loss: 48.70303916931152
Epoch: 214 , loss: 51.15890121459961
Epoch: 215 , loss: 58.31531524658203
Epoch: 216 , loss: 52.91571807861328
Epoch: 217 , loss: 50.07279586791992
Epoch: 218 , loss: 46.65008544921875
Epoch: 219 , loss: 45.3150749206543
Epoch: 220 , loss: 47.10740280151367
Epoch: 221 , loss: 47.831695556640625
Epoch: 222 , loss: 47.19715690612793
Epoch: 223 , loss: 50.87701988220215
Epoch: 224 , loss: 41.850791931152344
Epoch: 225 , loss: 46.13648986816406
Epoch: 226 , loss: 39.397817611694336
Epoch: 227 , loss: 43.573020935058594
Epoch: 228 , loss: 38.528221130371094
Epoch: 229 , loss: 44.3276252746582
Epoch: 230 , loss: 41.785282135009766
Epoch: 231 , loss: 44.973318099975586
Epoch: 232 , loss: 43.28142547607422
Epoch: 233 , loss: 38.6849422454834
Epoch: 234 , loss: 38.113996505737305
Epoch: 235 , loss: 45.978445053100586
Epoch: 236 , loss: 39.930870056152344
Epoch: 237 , loss: 38.72870635986328
Epoch: 238 , loss: 37.40564727783203
Epoch: 239 , loss: 39.39175605773926
Epoch: 240 , loss: 38.456756591796875
Epoch: 241 , loss: 39.97927474975586
Epoch: 242 , loss: 42.59111022949219
Epoch: 243 , loss: 35.96626091003418
Epoch: 244 , loss: 39.28248405456543
Epoch: 245 , loss: 42.70786666870117
Epoch: 246 , loss: 36.52967834472656
Epoch: 247 , loss: 37.1768798828125
Epoch: 248 , loss: 34.014339447021484
Epoch: 249 , loss: 39.391984939575195
Training complete. Saving file...

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Model saved in file: tmp/MIDAS
INFO:tensorflow:Restoring parameters from tmp/MIDAS
Model restored.

In [10]:
Xy_Yes_No_md

,Age_at_Surgery,Race,Surgery,Smoker,BMI,NAC,cT,pT,cT_or_pT,pN,Bx_Histology,Histology,Sample_weight_g_tumor,Tumor_digest_count_primary_tumor,Number_of_fragments_plated_tumor,OverallTILGrowth
0,69.0,1.0,2.0,0.0,19.700000,0.0,4.0,5.0,5.0,0.0,1.0,1.0,4.8900,120000000.0,24.0,1.0
1,78.0,1.0,1.0,1.0,31.770000,0.0,10.0,0.0,10.0,0.0,1.0,0.0,0.4400,225000.0,8.0,1.0
2,81.0,1.0,2.0,0.0,28.830000,0.0,1.0,6.0,1.0,0.0,1.0,1.0,0.0300,200000.0,4.0,0.0
3,74.0,1.0,2.0,1.0,44.290000,0.0,1.0,0.0,1.0,0.0,1.0,1.0,2.1100,30300000.0,18.0,0.0
4,57.0,0.0,1.0,3.0,47.140000,0.0,7.0,6.0,6.0,1.0,1.0,1.0,1.0000,23600000.0,18.0,1.0
5,67.0,1.0,1.0,1.0,21.440000,1.0,9.0,11.0,11.0,0.0,1.0,7.0,1.4400,30600000.0,24.0,1.0
6,77.0,1.0,1.0,2.0,22.200000,0.0,4.0,6.0,4.0,0.0,4.0,4.0,0.0000,2900000.0,8.0,1.0
7,69.0,1.0,1.0,1.0,26.910000,1.0,4.0,9.0,9.0,0.0,1.0,4.0,1.7000,4910000.0,3.0,1.0
8,82.0,1.0,1.0,1.0,27.130000,0.0,4.0,3.0,4.0,0.0,1.0,4.0,0.6500,1310000.0,24.0,1.0
9,91.0,1.0,1.0,0.0,24.540000,0.0,7.0,9.0,7.0,3.0,6.0,11.0,0.3400,1980000.0,18.0,1.0
10,79.0,3.0,2.0,0.0,28.860000,0.0,3.0,1.0,3.0,0.0,1.0,1.0,0.0500,217000.0,2.0,1.0
11,76.0,1.0,1.0,1.0,28.150000,1.0,4.0,11.0,4.0,0.0,1.0,4.0,1.5800,13700000.0,24.0,1.0
12,79.0,1.0,1.0,1.0,27.130000,1.0,4.0,2.0,4.0,0.0,1.0,1.0,0.6000,2500000.0,10.0,1.0
13,75.0,1.0,2.0,1.0,38.520000,0.0,1.0,6.0,1.0,0.0,1.0,1.0,0.1400,1040000.0,6.0,0.0
14,81.0,1.0,1.0,1.0,26.800000,0.0,7.0,6.0,7.0,0.0,1.0,1.0,0.5600,10700000.0,12.0,1.0
15,90.0,1.0,1.0,1.0,24.270000,1.0,3.0,11.0,11.0,2.0,1.0,1.0,0.4000,1680000.0,12.0,1.0
16,54.0,1.0,1.0,2.0,22.650000,0.0,4.0,5.0,4.0,0.0,1.0,7.0,1.8000,84000000.0,24.0,1.0
17,73.0,1.0,2.0,0.0,29.000000,0.0,3.0,1.0,3.0,0.0,0.0,4.0,0.4500,450000.0,18.0,1.0
18,79.0,1.0,1.0,1.0,28.100000,1.0,7.0,9.0,9.0,0.0,4.0,1.0,3.0878,18300000.0,24.0,1.0
19,79.0,1.0,1.0,1.0,26.710000,0.0,4.0,8.0,4.0,1.0,4.0,4.0,0.0400,300000.0,5.0,1.0
20,47.0,1.0,2.0,0.0,22.520000,1.0,1.0,6.0,1.0,0.0,1.0,1.0,0.0120,0.0,2.0,1.0
21,75.0,1.0,1.0,1.0,25.360000,0.0,1.0,9.0,9.0,0.0,4.0,4.0,1.1000,16800000.0,24.0,1.0
22,82.0,1.0,1.0,1.0,3.555427,0.0,4.0,1.0,4.0,0.0,1.0,1.0,8.5600,10100000.0,24.0,0.0
23,61.0,1.0,1.0,2.0,26.280000,0.0,7.0,9.0,7.0,1.0,1.0,7.0,1.1700,3500000.0,12.0,1.0
24,78.0,1.0,1.0,1.0,26.330000,0.0,1.0,4.0,1.0,0.0,1.0,4.0,0.1700,600000.0,5.0,0.0
25,63.0,1.0,2.0,0.0,33.220000,0.0,3.0,2.0,3.0,0.0,1.0,1.0,0.0000,1000000.0,12.0,0.0
26,57.0,1.0,2.0,1.0,36.750000,0.0,3.0,1.0,3.0,3.0,1.0,1.0,1.2000,5300000.0,16.0,0.0
27,63.0,1.0,1.0,1.0,49.240000,0.0,4.0,9.0,9.0,0.0,4.0,4.0,17.3400,100000000.0,24.0,1.0
28,69.0,1.0,1.0,2.0,28.950000,1.0,1.0,2.0,2.0,0.0,1.0,1.0,0.0000,0.0,0.0,0.0
29,75.0,1.0,1.0,1.0,37.000000,0.0,1.0,9.0,9.0,0.0,1.0,1.0,0.0700,180000.0,3.0,0.0
30,66.0,1.0,1.0,1.0,28.690000,0.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0000,0.0,0.0,0.0
31,70.0,1.0,2.0,3.0,30.670000,1.0,10.0,0.0,0.0,0.0,1.0,1.0,0.0000,0.0,0.0,0.0

In [11]:
# save to csv file

# 
Xy_Yes_No_md.to_csv('data/Xy_test_Yes_No_md.csv', index=False)

In [12]:
# compare 

Xy_Yes_No.compare(Xy_Yes_No_md, keep_shape=True, keep_equal=True)

   Age_at_Surgery       Race       Surgery       Smoker          BMI  \
             self other self other    self other   self other   self
0            69.0  69.0  1.0   1.0     2.0   2.0    0.0   0.0  19.70
1            78.0  78.0  1.0   1.0     1.0   1.0    1.0   1.0  31.77
2            81.0  81.0  1.0   1.0     2.0   2.0    0.0   0.0  28.83
3            74.0  74.0  1.0   1.0     2.0   2.0    1.0   1.0  44.29
4            57.0  57.0  0.0   0.0     1.0   1.0    3.0   3.0  47.14
5            67.0  67.0  1.0   1.0     1.0   1.0    1.0   1.0  21.44
6            77.0  77.0  1.0   1.0     1.0   1.0    2.0   2.0  22.20
7            69.0  69.0  1.0   1.0     1.0   1.0    1.0   1.0  26.91
8            82.0  82.0  1.0   1.0     1.0   1.0    1.0   1.0  27.13
9            91.0  91.0  1.0   1.0     1.0   1.0    0.0   0.0  24.54
10           79.0  79.0  3.0   3.0     2.0   2.0    0.0   0.0  28.86
11           76.0  76.0  1.0   1.0     1.0   1.0    1.0   1.0  28.15
12           79.0  79.0  1.0   1.0     1.0   1.0    1.0   1.0  27.13
13           75.0  75.0  1.0   1.0     2.0   2.0    1.0   1.0  38.52
14           81.0  81.0  1.0   1.0     1.0   1.0    1.0   1.0  26.80
15           90.0  90.0  1.0   1.0     1.0   1.0    1.0   1.0  24.27
16           54.0  54.0  1.0   1.0     1.0   1.0    2.0   2.0  22.65
17           73.0  73.0  1.0   1.0     2.0   2.0    0.0   0.0  29.00
18           79.0  79.0  1.0   1.0     1.0   1.0    1.0   1.0  28.10
19           79.0  79.0  1.0   1.0     1.0   1.0    1.0   1.0  26.71
20           47.0  47.0  1.0   1.0     2.0   2.0    0.0   0.0  22.52
21           75.0  75.0  1.0   1.0     1.0   1.0    1.0   1.0  25.36
22           82.0  82.0  1.0   1.0     1.0   1.0    1.0   1.0    NaN
23           61.0  61.0  1.0   1.0     1.0   1.0    2.0   2.0  26.28
24           78.0  78.0  1.0   1.0     1.0   1.0    1.0   1.0  26.33
25           63.0  63.0  1.0   1.0     2.0   2.0    0.0   0.0  33.22
26           57.0  57.0  1.0   1.0     2.0   2.0    1.0   1.0  36.75
27           63.0  63.0  1.0   1.0     1.0   1.0    1.0   1.0  49.24
28           69.0  69.0  1.0   1.0     1.0   1.0    2.0   2.0  28.95
29           75.0  75.0  1.0   1.0     1.0   1.0    1.0   1.0  37.00
30           66.0  66.0  1.0   1.0     1.0   1.0    1.0   1.0  28.69
31           70.0  70.0  1.0   1.0     2.0   2.0    3.0   3.0  30.67

               NAC          cT          pT       cT_or_pT         pN        \
        other self other  self other  self other     self other self other
0   19.700000  0.0   0.0   4.0   4.0   5.0   5.0      5.0   5.0  NaN   0.0
1   31.770000  0.0   0.0  10.0  10.0   0.0   0.0     10.0  10.0  0.0   0.0
2   28.830000  0.0   0.0   1.0   1.0   NaN   6.0      1.0   1.0  NaN   0.0
3   44.290000  0.0   0.0   1.0   1.0   NaN   0.0      1.0   1.0  NaN   0.0
4   47.140000  NaN   0.0   NaN   7.0   6.0   6.0      6.0   6.0  1.0   1.0
5   21.440000  1.0   1.0   9.0   9.0  11.0  11.0     11.0  11.0  0.0   0.0
6   22.200000  0.0   0.0   4.0   4.0   6.0   6.0      4.0   4.0  0.0   0.0
7   26.910000  1.0   1.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
8   27.130000  0.0   0.0   4.0   4.0   3.0   3.0      4.0   4.0  0.0   0.0
9   24.540000  0.0   0.0   7.0   7.0   9.0   9.0      7.0   7.0  3.0   3.0
10  28.860000  0.0   0.0   3.0   3.0   NaN   1.0      3.0   3.0  NaN   0.0
11  28.150000  1.0   1.0   4.0   4.0  11.0  11.0      4.0   4.0  0.0   0.0
12  27.130000  1.0   1.0   4.0   4.0   2.0   2.0      4.0   4.0  0.0   0.0
13  38.520000  0.0   0.0   1.0   1.0   NaN   6.0      1.0   1.0  NaN   0.0
14  26.800000  0.0   0.0   7.0   7.0   6.0   6.0      7.0   7.0  0.0   0.0
15  24.270000  1.0   1.0   3.0   3.0  11.0  11.0     11.0  11.0  2.0   2.0
16  22.650000  0.0   0.0   4.0   4.0   5.0   5.0      4.0   4.0  0.0   0.0
17  29.000000  0.0   0.0   3.0   3.0   NaN   1.0      3.0   3.0  NaN   0.0
18  28.100000  1.0   1.0   7.0   7.0   9.0   9.0      9.0   9.0  0.0   0.0
19  26.710000  0.0   0.0   4.0   4.0   8.0   8.0      4.0   4.0  1.0   1.0
20  22.520000  1.0   1.0   1.0   1.0   NaN   6.0      1.0   1.0  NaN   0.0
21  25.360000  0.0   0.0   1.0   1.0   9.0   9.0      9.0   9.0  0.0   0.0
22   3.555427  0.0   0.0   4.0   4.0   1.0   1.0      4.0   4.0  0.0   0.0
23  26.280000  0.0   0.0   7.0   7.0   9.0   9.0      7.0   7.0  1.0   1.0
24  26.330000  0.0   0.0   1.0   1.0   4.0   4.0      1.0   1.0  0.0   0.0
25  33.220000  0.0   0.0   3.0   3.0   2.0   2.0      3.0   3.0  NaN   0.0
26  36.750000  0.0   0.0   3.0   3.0   1.0   1.0      3.0   3.0  NaN   3.0
27  49.240000  0.0   0.0   4.0   4.0   9.0   9.0      9.0   9.0  0.0   0.0
28  28.950000  1.0   1.0   1.0   1.0   2.0   2.0      2.0   2.0  0.0   0.0
29  37.000000  0.0   0.0   NaN   1.0   9.0   9.0      9.0   9.0  0.0   0.0
30  28.690000  0.0   0.0   4.0   4.0   0.0   0.0      4.0   4.0  0.0   0.0
31  30.670000  1.0   1.0   NaN  10.0   0.0   0.0      0.0   0.0  NaN   0.0

   Bx_Histology       Histology       Sample_weight_g_tumor           \
           self other      self other                  self    other
0           1.0   1.0       1.0   1.0                4.8900   4.8900
1           1.0   1.0       0.0   0.0                0.4400   0.4400
2           1.0   1.0       1.0   1.0                0.0300   0.0300
3           1.0   1.0       1.0   1.0                2.1100   2.1100
4           1.0   1.0       1.0   1.0                1.0000   1.0000
5           1.0   1.0       7.0   7.0                1.4400   1.4400
6           4.0   4.0       4.0   4.0                0.0000   0.0000
7           1.0   1.0       4.0   4.0                1.7000   1.7000
8           1.0   1.0       4.0   4.0                0.6500   0.6500
9           6.0   6.0      11.0  11.0                0.3400   0.3400
10          1.0   1.0       1.0   1.0                0.0500   0.0500
11          1.0   1.0       4.0   4.0                1.5800   1.5800
12          1.0   1.0       1.0   1.0                0.6000   0.6000
13          1.0   1.0       1.0   1.0                0.1400   0.1400
14          1.0   1.0       1.0   1.0                0.5600   0.5600
15          1.0   1.0       1.0   1.0                0.4000   0.4000
16          1.0   1.0       7.0   7.0                1.8000   1.8000
17          0.0   0.0       4.0   4.0                0.4500   0.4500
18          4.0   4.0       1.0   1.0                3.0878   3.0878
19          4.0   4.0       4.0   4.0                0.0400   0.0400
20          1.0   1.0       1.0   1.0                0.0120   0.0120
21          4.0   4.0       4.0   4.0                1.1000   1.1000
22          1.0   1.0       1.0   1.0                8.5600   8.5600
23          1.0   1.0       7.0   7.0                1.1700   1.1700
24          1.0   1.0       4.0   4.0                0.1700   0.1700
25          1.0   1.0       1.0   1.0                0.0000   0.0000
26          1.0   1.0       1.0   1.0                1.2000   1.2000
27          4.0   4.0       4.0   4.0               17.3400  17.3400
28          1.0   1.0       1.0   1.0                0.0000   0.0000
29          1.0   1.0       1.0   1.0                0.0700   0.0700
30          0.0   0.0       NaN   4.0                0.0000   0.0000
31          1.0   1.0       1.0   1.0                0.0000   0.0000

   Tumor_digest_count_primary_tumor               \
                               self        other
0                       120000000.0  120000000.0
1                          225000.0     225000.0
2                          200000.0     200000.0
3                        30300000.0   30300000.0
4                        23600000.0   23600000.0
5                        30600000.0   30600000.0
6                         2900000.0    2900000.0
7                         4910000.0    4910000.0
8                         1310000.0    1310000.0
9                         1980000.0    1980000.0
10                         217000.0     217000.0
11                       13700000.0   13700000.0
12                        2500000.0    2500000.0
13                        1040000.0    1040000.0
14                       10700000.0   10700000.0
15                        1680000.0    1680000.0
16                       84000000.0   84000000.0
17                         450000.0     450000.0
18                       18300000.0   18300000.0
19                         300000.0     300000.0
20                              0.0          0.0
21                       16800000.0   16800000.0
22                       10100000.0   10100000.0
23                        3500000.0    3500000.0
24                         600000.0     600000.0
25                        1000000.0    1000000.0
26                        5300000.0    5300000.0
27                      100000000.0  100000000.0
28                              0.0          0.0
29                         180000.0     180000.0
30                              0.0          0.0
31                              0.0          0.0

   Number_of_fragments_plated_tumor       OverallTILGrowth
                               self other             self other
0                              24.0  24.0              1.0   1.0
1                               8.0   8.0              1.0   1.0
2                               4.0   4.0              0.0   0.0
3                              18.0  18.0              0.0   0.0
4                              18.0  18.0              1.0   1.0
5                              24.0  24.0              1.0   1.0
6                               8.0   8.0              1.0   1.0
7                               3.0   3.0              1.0   1.0
8                              24.0  24.0              1.0   1.0
9                              18.0  18.0              1.0   1.0
10                              2.0   2.0              1.0   1.0
11                             24.0  24.0              1.0   1.0
12                             10.0  10.0              1.0   1.0
13                              6.0   6.0              0.0   0.0
14                             12.0  12.0              1.0   1.0
15                             12.0  12.0              1.0   1.0
16                             24.0  24.0              1.0   1.0
17                             18.0  18.0              1.0   1.0
18                             24.0  24.0              1.0   1.0
19                              5.0   5.0              1.0   1.0
20                              2.0   2.0              1.0   1.0
21                             24.0  24.0              1.0   1.0
22                             24.0  24.0              0.0   0.0
23                             12.0  12.0              1.0   1.0
24                              5.0   5.0              0.0   0.0
25                             12.0  12.0              0.0   0.0
26                             16.0  16.0              0.0   0.0
27                             24.0  24.0              1.0   1.0
28                              0.0   0.0              0.0   0.0
29                              3.0   3.0              0.0   0.0
30                              0.0   0.0              0.0   0.0
31                              0.0   0.0              0.0   0.0